# Generated by Django 5.1.4 on 2025-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disputes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="buyer_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="chat_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dispute",
            name="partial_refund_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolution_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RELEASE_TO_VENDOR", "Release to Vendor"),
                    ("REFUND_TO_BUYER", "Refund to Buyer"),
                    ("PARTIAL_REFUND", "Partial Refund"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="vendor_statement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="disputeevidence",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("SCREENSHOT", "Screenshot"),
                    ("BLOCKCHAIN_TX", "Blockchain Transaction"),
                    ("COMMUNICATION", "Communication Log"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("INVESTIGATING", "Under Investigation"),
                    ("AWAITING_VENDOR", "Awaiting Vendor Response"),
                    ("AWAITING_BUYER", "Awaiting Buyer Response"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
