# Generated by Django 5.1.4 on 2025-08-26 08:56

from decimal import Decimal
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_add_all_missing_fields'),
    ]

    operations = [
        # Add new balance fields
        migrations.AddField(
            model_name='wallet',
            name='balance_btc',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('0.00000000'),
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))]
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_xmr',
            field=models.DecimalField(
                decimal_places=12,
                default=Decimal('0.000000000000'),
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))]
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='escrow_btc',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('0.00000000'),
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))]
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='escrow_xmr',
            field=models.DecimalField(
                decimal_places=12,
                default=Decimal('0.000000000000'),
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))]
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawal_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='two_fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_withdrawal_limit_btc',
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal('1.00000000'),
                max_digits=16
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='daily_withdrawal_limit_xmr',
            field=models.DecimalField(
                decimal_places=12,
                default=Decimal('100.000000000000'),
                max_digits=16
            ),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
