# Generated by Django 5.1.4 on 2025-08-26 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_auto_20250826_0856'),
    ]

    operations = [
        # Add missing fields for database compatibility
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(blank=True, default='BTC', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default=Decimal('0.00000000'),
                max_digits=20,
                null=True
            ),
        ),
    ]
