# Generated by Django 5.1.4 on 2025-08-24 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_bond_amount_vendor_bond_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='completed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='disputed_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_header',
            field=models.TextField(blank=True, help_text='BBCode supported for rich formatting'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='shipping_info',
            field=models.TextField(blank=True, help_text='Shipping information (BBCode supported)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='terms_conditions',
            field=models.TextField(blank=True, help_text='Your terms and conditions (BBCode supported)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trust_score',
            field=models.IntegerField(default=1, help_text='Calculated trust score (1-10)'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['trust_score'], name='vendors_ven_trust_s_4fa389_idx'),
        ),
    ]
