# Generated by Django 5.1.4 on 2025-08-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="vendor",
            name="vendors_active_approved_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendor",
            name="vendors_trust_score_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendor",
            name="vendors_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendorrating",
            name="vendor_rating_idx",
        ),
        migrations.RemoveIndex(
            model_name="vendorrating",
            name="vendor_rating_recent_idx",
        ),
    ]
