# Generated by Django 5.1.4 on 2025-08-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_indexes"),
        ("vendors", "0008_remove_vendor_vendors_active_approved_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_user_recent_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_status_recent_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orderitem_order_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orderitem_product_idx",
        ),
        migrations.AddField(
            model_name="order",
            name="auto_finalize_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="currency_used",
            field=models.CharField(
                blank=True, choices=[("BTC", "Bitcoin"), ("XMR", "Monero")], max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="escrow_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_orders",
                to="vendors.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Payment"),
                    ("PAID", "Paid"),
                    ("PROCESSING", "Processing"),
                    ("LOCKED", "Funds Locked in Escrow"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DISPUTED", "Disputed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_xmr",
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price_xmr",
            field=models.DecimalField(decimal_places=12, max_digits=20),
        ),
    ]
