# Generated by Django 5.1.4 on 2025-08-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="prod_vendor_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="prod_cat_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_stock_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_price_btc_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_price_xmr_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_created_desc_idx",
        ),
    ]
